# Generated by Django 2.0.3 on 2018-04-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beaches',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('latX', models.DecimalField(decimal_places=2, max_digits=5, max_length=30)),
                ('latY', models.DecimalField(decimal_places=2, max_digits=5, max_length=30)),
                ('cond', models.CharField(choices=[('B', 'Beginner'), ('M', 'Medium'), ('A', 'Advanced')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AddField(
            model_name='users',
            name='exp',
            field=models.CharField(choices=[('B', 'Beginner'), ('M', 'Medium'), ('A', 'Advanced')], default='D', max_length=30),
            preserve_default=False,
        ),
    ]
